app/(api)/api/create-module/route.ts
app/(api)/api/get-modules/route.ts
components/PostItem.tsx
lib/actions/user.actions.ts
package-lock.json
package.json

Use postAttachmentbucket for module

Delete an axios package

---

components/AddQuestionForm.tsx
types/schema.ts

Use Student | Job seeker | Employer

Add Categories on attractive question

---

components/OverView.tsx
components/PayStatus.tsx
components/PaymentButton.tsx
lib/store/useAuthStore.ts

Implement checks for premium access in the OverView component, standardize transaction references in the PaymentButton, and ensure user payment status updates upon course purchases. These changes improve user experience and streamline payment processing.

Enhance premium access management and payment handling

---

components/BodySection.tsx
components/EditProfilePage.tsx
components/Header_description.tsx
components/OverView.tsx
components/ProfileContainer.tsx
lib/actions/user.actions.ts
lib/store/useAuthStore.ts
package-lock.json
package.json

Improve layout and responsiveness of the Header_description and BodySection components. Remove axios dependency and add user profile update functionality with validation. Introduce ProfileContainer for toggling between viewing and editing profiles. Refactor related components for better user experience.

Enhance user profile management and UI components

---

components/EditProfilePage.tsx
components/OverView.tsx
components/Posts.tsx
components/ProfileContainer.tsx
lib/actions/user.actions.ts

Enhance the layout and responsiveness of profile-related components, improve error logging in the Posts component, and simplify user data updates in the updateUserProfile method.

Refactor profile components for improved user experience and error handling

---

components/EditProfilePage.tsx
components/OverView.tsx
lib/actions/user.actions.ts
lib/store/useAuthStore.ts

Enhance the EditProfilePage with toast notifications for success and error messages, improve the OverView component's styling, and ensure user data is validated and cleaned before updates. Integrate user state management with localStorage in the useAuthStore.

Refactor profile editing and overview components with notifications

---

components/CourseCard.tsx
components/CourseList.tsx

Change the messaging for locked courses to prompt users to upgrade their membership for access.

Update locked course message to encourage membership upgrade

---

components/AdminSidebar.tsx
lib/actions/user.actions.ts

Implement logout functionality in the AdminSidebar and enhance the referral processing logic to robustly handle user retrieval and referral code extraction.

Add logout functionality and improve referral processing logic

---

components/JobList.tsx
package-lock.json

This pull request does not introduce any code changes. It serves as a placeholder or for documentation purposes.

No code changes detected

---

app/(dashboard)/dashboard/help/page.tsx
app/(pages)/contact/page.tsx
components/ContactForm.tsx
components/ThankYouMessage.tsx
components/ui/dialog.tsx
lib/store/emailService.ts
package-lock.json
package.json

Refactor the contact page to utilize new `ContactForm` and `ThankYouMessage` components for better form handling and user feedback. Introduce an `emailService` module for API communication and update the dialog components for improved user interaction. A new Help page with a contact support modal is also added.

Refactor contact page and enhance user feedback components

---

app/(dashboard)/dashboard/help/page.tsx
app/globals.css
app/layout.tsx
components/InputContact.tsx
components/OverView.tsx
components/ShareSomething.tsx
package-lock.json

Improve the visual appearance of the Contact Form by adding a background color and increasing the spacing between elements.

Enhance Contact Form styling with background color and increased spacing

---

components/SearchResults.tsx
components/ShareSomething.tsx
components/ui/avatar.tsx
lib/actions/user.actions.ts
package-lock.json
package.json

Introduce the SearchResults component for improved search result display, including loading and no results states. Refactor the ShareSomething component to enhance search capabilities, implement pagination, and provide better user feedback. Add Avatar component utilizing @radix-ui/react-avatar for user images and fallbacks. Include date-fns for date formatting.

Enhance search functionality with new components and dependencies

---

components/SearchResults.tsx

Simplify the avatar rendering logic in the SearchResults component to improve readability and maintainability.

Refactor SearchResults component for avatar rendering

---

components/SearchResults.tsx

Eliminate an unused import of Link and enhance the date formatting logic in the SearchResults component for better clarity.

Remove unused Link import and update date formatting in SearchResults component

---

app/(dashboard)/dashboard/help/page.tsx

Remove the ContactFormWithToast component and directly integrate the ContactForm into the Help component for a more streamlined implementation.

Refactor Help component to integrate ContactForm directly

---

app/layout.tsx
package-lock.json
package.json

Add the @vercel/analytics package and integrate it into the RootLayout, enhancing the HTML structure for better analytics tracking.

Integrate Vercel Analytics into the application

---

components/SearchResults.tsx

Replace the Avatar component with a custom placeholder and update the styling for improved visual consistency.

Refactor SearchResults component with custom placeholder

---

components/Footer.tsx
package-lock.json
package.json

Correct typos in the className of the Footer component and update the react-hot-toast package to the latest version.

Fix typos in Footer component and update react-hot-toast version

---

app/(api)/api/proxy-flutterwave/initiate/route.ts
components/PersonSidebar.tsx
components/reset-password-email.tsx
lib/actions/user.actions.ts

Change all relevant URLs in the payment initiation, referral link, reset password email, and verification processes to point to the production domain for consistency and proper functionality.

Update URLs to production domain for consistency

---

lib/actions/user.actions.ts

Improve the referral system by adding logging for updates to referrer points and referred users, along with error handling to ensure robust updates to the referrer document.

Enhance referral system with logging and error handling

---

app/(api)/api/proxy-flutterwave/payment-status/route.ts

Update the payment status route to calculate and store referral fees directly in the database, improving efficiency by eliminating the previous method of updating referral points.

Refactor payment status route to update referral fees in the database directly

---

app/(api)/api/proxy-flutterwave/payment-status/route.ts
components/OverView.tsx

Improve responsiveness of the OverView component layout and streamline the referral fee calculation by removing unnecessary exchange rate fetching.

Refactor OverView component and simplify referral fee calculation

---

types/schema.ts

Introduce TypeScript types and interfaces to enhance type safety for questions, answers, user responses, and temperament results.

Add types for questions, answers, user responses, and temperament results

---

components/SignupForm.tsx
components/Video.tsx
lib/actions/user.actions.ts
lib/store/useAuthStore.ts

Enhance error handling and messaging in the signup process, improve progress update logic in the Video component, and refine the email existence check in the registration function.

Refactor user registration and error handling improvements

---

app/(dashboard)/dashboard/fundings/page.tsx
app/(dashboard)/dashboard/scholarships/page.tsx
components/BaseInfoStep.tsx
components/JobList.tsx
components/SearchScholarship.tsx
components/jobSearch.tsx
lib/actions/user.actions.ts
lib/utils.ts
types/schema.ts

Implement fuzzy search utilities and advanced filters for job and scholarship searches. Refactor multiple components to enhance user experience, improve error handling, and ensure better readability.

Enhance search functionalities and improve component design

---

app/admin/page.tsx
lib/actions/user.actions.ts

Enhance the admin experience by adding user search, pagination, and delete capabilities, along with error handling for user deletion.

Implement user management features with search, pagination, and delete functionality

---

app/admin/questions/page.tsx
components/OverView.tsx
lib/actions/user.actions.ts
utils/sendQuestionEmail.ts

Modify the sidebar

---

app/admin/page.tsx
lib/actions/user.actions.ts

Remove notification state and related logic from user management. Update the `getAllUsers` query to order results by creation date.

Refactor user management and update user query sorting

---

app/(api)/api/proxy-flutterwave/payment-status/route.ts
app/admin/payment/page.tsx
lib/actions/user.actions.ts
types/schema.ts

Introduce a limit to user queries in the payment status route to enhance performance and prevent excessive data retrieval.

Add limit to user queries in payment status route

---

app/layout.tsx

Enhance the user authentication process by streamlining login and registration, improving error handling, and updating the user interface for better usability.

Improve user authentication flow

---

public/manifest.json

Include Android and iOS platforms in the related applications section of the manifest.json file.

Update related applications in manifest.json for Android and iOS

---

public/manifest.json

Change the orientation in the manifest to portrait and eliminate the related applications section.

Update manifest orientation to portrait and remove related applications
